name: Deploy FastAPI to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Render
        run: echo "${{ secrets.RENDER_API_KEY }}" | docker login --username ${{ secrets.RENDER_USERNAME }} --password-stdin registry.render.com

      - name: Build & Push Docker Image
        run: |
          docker build -t registry.render.com/my-fastapi-app .
          docker push registry.render.com/my-fastapi-app

      - name: Deploy to Render
        run: curl -X POST "https://api.render.com/v1/services/my-fastapi-app/deploys" \
             -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
             -H "Content-Type: application/json"
